server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://10.23.103.132:3306/message-router
    username: root
    password: Bb123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: 10.23.103.132
    port: 5672
    username: rabbit
    password: 12345678
    virtual-host: iot
#    listener:
#      simple:
#        acknowledge-mode: auto
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 2s

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml