server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/message-router
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: iot
#    listener:
#      simple:
#        acknowledge-mode: auto
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 2s

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml